In [ ]:
#wap a program to print a numpy array...using python list, display the array and print the shape and datatype of array

import numpy as np

list = [10, 20, 30, 40, 50]
arr = np.array(list)

print(arr)
print(arr.shape)
print("Data Type:" ,arr.dtype)


[10 20 30 40 50]
(5,)
Data Type: int64


In [ ]:

import numpy as np

matrix1 = np.ones((2, 5))

print("Matrix:", matrix1)
print(matrix1.shape)


Matrix: [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)


In [ ]:

array = np.arange(1, 13)
reshaped_arr = array.reshape(3, 4)

print("Original Array:", array)
print("Original Shape:", array.shape)

print("Reshaped Array:", reshaped_arr)
print("Reshaped Shape:", reshaped_arr.shape)


Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Original Shape: (12,)
Reshaped Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped Shape: (3, 4)


In [ ]:
import numpy as np
array1= np.random.randint(1,100,10)
print(array1)
print("Minimum:", array1.min())
print("Maximum:", array1.max())
print("Mean:", array1.mean())
print("Sum:", array1.sum())

[47  7  3 18 34 59 81 70 54 65]
Minimum: 3
Maximum: 81
Mean: 43.8
Sum: 438


In [ ]:
import pandas as pd

data = {
    "Student_Name": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [85, 90, 78, 92]
}

df = pd.DataFrame(data)

print("DataFrame:", df)
print(df.dtypes)


DataFrame:   Student_Name  Marks
0        Alice     85
1          Bob     90
2      Charlie     78
3        David     92
Student_Name    object
Marks            int64
dtype: object


In [ ]:
import pandas as pd

df = pd.read_csv("/content/student.csv")

print(df.head())
print(df.iloc[-5:, -5:])


   Student_ID Student_Name  Marks  Age       City
0           1        Alice     85   20      Delhi
1           2          Bob     90   21     Mumbai
2           3      Charlie     78   19    Chennai
3           4        David     92   22    Kolkata
4           5          Eva     88   20  Hyderabad
   Student_ID Student_Name  Marks  Age       City
5           6        Frank     75   21       Pune
6           7        Grace     95   23  Bangalore
7           8        Helen     80   20     Jaipur
8           9          Ian     70   22  Ahmedabad
9          10         Jack     89   21      Noida


In [ ]:
import pandas as pd
df = pd.read_csv("/content/student.csv")

print("Number of Rows:", df.shape[0])

print("\nMissing Values in Each Column:")
print(df.isnull().sum())


Number of Rows: 10

Missing Values in Each Column:
Student_ID      0
Student_Name    0
Marks           0
Age             0
City            0
dtype: int64


In [ ]:
import pandas as pd
df = pd.read_csv("/content/student.csv")
print("DataFrame:\n", df)
print("\nStatistical Summary:\n")
print(df.describe())


DataFrame:
    Student_ID Student_Name  Marks  Age       City
0           1        Alice     85   20      Delhi
1           2          Bob     90   21     Mumbai
2           3      Charlie     78   19    Chennai
3           4        David     92   22    Kolkata
4           5          Eva     88   20  Hyderabad
5           6        Frank     75   21       Pune
6           7        Grace     95   23  Bangalore
7           8        Helen     80   20     Jaipur
8           9          Ian     70   22  Ahmedabad
9          10         Jack     89   21      Noida

Statistical Summary:

       Student_ID     Marks        Age
count    10.00000  10.00000  10.000000
mean      5.50000  84.20000  20.900000
std       3.02765   8.10761   1.197219
min       1.00000  70.00000  19.000000
25%       3.25000  78.50000  20.000000
50%       5.50000  86.50000  21.000000
75%       7.75000  89.75000  21.750000
max      10.00000  95.00000  23.000000
